import { JobPosting } from '@/types';

export const mockJobs: JobPosting[] = [
  {
    id: '1',
    title: '자사 웹 서비스 프론트엔드 개발',
    company: '(주)테크스타트',
    skills: ['React', 'TypeScript', 'Next.js'],
    location: '서울 구로구',
    salary: {
      min: 3500,
      max: 5000,
    },
    duration: '3개월',
    budget: '3,000만원',
    deadline: 'D-7',
    type: '외주',
    description: '프론트엔드 개발자를 모집합니다.',
    requirements: ['경력 3년 이상', '관련 학과 졸업'],
    postDate: new Date(),
  },
  {
    id: '2',
    title: '금융 플랫폼 백엔드 개발자',
    company: '(주)핀테크솔루션',
    skills: ['Java', 'Spring Boot', 'MSA'],
    location: '서울 강남구',
    salary: {
      min: 4500,
      max: 6000,
    },
    duration: '6개월',
    budget: '5,000만원',
    deadline: 'D-5',
    type: '상주',
    description: '백엔드 개발자를 모집합니다.',
    requirements: ['경력 5년 이상', 'MSA 경험'],
    postDate: new Date(),
  },
  {
    id: '3',
    title: '모바일 앱 UI/UX 디자이너',
    company: '(주)모바일테크',
    skills: ['Figma', 'Adobe XD', 'Sketch'],
    location: '서울 서초구',
    salary: {
      min: 3000,
      max: 4500,
    },
    duration: '4개월',
    budget: '2,800만원',
    deadline: 'D-3',
    type: '외주',
    description: 'UI/UX 디자이너를 모집합니다.',
    requirements: ['포트폴리오 필수', '앱 디자인 경험'],
    postDate: new Date(),
  },
  {
    id: '4',
    title: '블록체인 플랫폼 개발자',
    company: '(주)블록테크',
    skills: ['Solidity', 'Web3.js', 'React'],
    location: '서울 성동구',
    salary: {
      min: 5000,
      max: 7000,
    },
    duration: '12개월',
    budget: '8,000만원',
    deadline: 'D-10',
    type: '상주',
    description: '블록체인 개발자를 모집합니다.',
    requirements: ['블록체인 개발 경험', 'Smart Contract 개발 경험'],
    postDate: new Date(),
  },
];