-- ===================================================================
-- Insert 100 Freelancer Records with Users Data
-- JobKorea Billboard Database
-- ===================================================================

USE jobtracker;

-- Insert 100 Users first (required for freelancers table foreign key)
INSERT INTO users (username, email, password_hash, full_name, phone, role, status, bio, location, created_at) VALUES
-- 개발자 (40명)
('dev001', 'kim.frontend@email.com', '$2b$10$hashedpassword1', '김프론트', '010-1234-0001', 'freelancer', 'active', 'React와 TypeScript 전문 프론트엔드 개발자', '서울', NOW()),
('dev002', 'lee.backend@email.com', '$2b$10$hashedpassword2', '이백엔드', '010-1234-0002', 'freelancer', 'active', 'Node.js와 Spring Boot 백엔드 전문가', '경기', NOW()),
('dev003', 'park.fullstack@email.com', '$2b$10$hashedpassword3', '박풀스택', '010-1234-0003', 'freelancer', 'active', '풀스택 개발자로 MERN 스택 전문', '부산', NOW()),
('dev004', 'choi.mobile@email.com', '$2b$10$hashedpassword4', '최모바일', '010-1234-0004', 'freelancer', 'active', 'React Native와 Flutter 모바일 앱 개발', '대구', NOW()),
('dev005', 'jung.python@email.com', '$2b$10$hashedpassword5', '정파이썬', '010-1234-0005', 'freelancer', 'active', 'Python과 Django를 활용한 웹 개발', '인천', NOW()),
('dev006', 'kang.java@email.com', '$2b$10$hashedpassword6', '강자바', '010-1234-0006', 'freelancer', 'active', 'Java Spring 기반 엔터프라이즈 개발', '광주', NOW()),
('dev007', 'yoon.react@email.com', '$2b$10$hashedpassword7', '윤리액트', '010-1234-0007', 'freelancer', 'active', 'React 생태계 전문가', '대전', NOW()),
('dev008', 'lim.vue@email.com', '$2b$10$hashedpassword8', '임뷰', '010-1234-0008', 'freelancer', 'active', 'Vue.js와 Nuxt.js 전문 개발자', '울산', NOW()),
('dev009', 'han.angular@email.com', '$2b$10$hashedpassword9', '한앵귤러', '010-1234-0009', 'freelancer', 'active', 'Angular 프레임워크 전문가', '세종', NOW()),
('dev010', 'oh.nodejs@email.com', '$2b$10$hashedpassword10', '오노드', '010-1234-0010', 'freelancer', 'active', 'Node.js 백엔드 및 API 개발', '서울', NOW()),
('dev011', 'shin.devops@email.com', '$2b$10$hashedpassword11', '신데브옵스', '010-1234-0011', 'freelancer', 'active', 'AWS 클라우드 및 DevOps 전문가', '경기', NOW()),
('dev012', 'kwon.db@email.com', '$2b$10$hashedpassword12', '권디비', '010-1234-0012', 'freelancer', 'active', '데이터베이스 설계 및 최적화 전문', '부산', NOW()),
('dev013', 'seo.ai@email.com', '$2b$10$hashedpassword13', '서에이아이', '010-1234-0013', 'freelancer', 'active', 'AI/ML 모델 개발 및 데이터 분석', '대구', NOW()),
('dev014', 'moon.blockchain@email.com', '$2b$10$hashedpassword14', '문블록체인', '010-1234-0014', 'freelancer', 'active', '블록체인 DApp 개발자', '인천', NOW()),
('dev015', 'jang.security@email.com', '$2b$10$hashedpassword15', '장시큐리티', '010-1234-0015', 'freelancer', 'active', '보안 및 해킹 방어 전문가', '광주', NOW()),
('dev016', 'song.unity@email.com', '$2b$10$hashedpassword16', '송유니티', '010-1234-0016', 'freelancer', 'active', 'Unity 게임 개발자', '대전', NOW()),
('dev017', 'go.flutter@email.com', '$2b$10$hashedpassword17', '고플러터', '010-1234-0017', 'freelancer', 'active', 'Flutter 크로스플랫폼 개발', '울산', NOW()),
('dev018', 'nam.swift@email.com', '$2b$10$hashedpassword18', '남스위프트', '010-1234-0018', 'freelancer', 'active', 'iOS Swift 네이티브 앱 개발', '세종', NOW()),
('dev019', 'woo.kotlin@email.com', '$2b$10$hashedpassword19', '우코틀린', '010-1234-0019', 'freelancer', 'active', 'Android Kotlin 개발자', '서울', NOW()),
('dev020', 'ryu.php@email.com', '$2b$10$hashedpassword20', '류피에이치피', '010-1234-0020', 'freelancer', 'active', 'PHP Laravel 웹 개발자', '경기', NOW()),
('dev021', 'hong.docker@email.com', '$2b$10$hashedpassword21', '홍도커', '010-1234-0021', 'freelancer', 'active', 'Docker 컨테이너 및 쿠버네티스', '부산', NOW()),
('dev022', 'cho.graphql@email.com', '$2b$10$hashedpassword22', '조그래프큐엘', '010-1234-0022', 'freelancer', 'active', 'GraphQL API 설계 전문가', '대구', NOW()),
('dev023', 'ahn.mongodb@email.com', '$2b$10$hashedpassword23', '안몽고디비', '010-1234-0023', 'freelancer', 'active', 'MongoDB 및 NoSQL 데이터베이스', '인천', NOW()),
('dev024', 'yoo.redis@email.com', '$2b$10$hashedpassword24', '유레디스', '010-1234-0024', 'freelancer', 'active', 'Redis 캐싱 및 성능 최적화', '광주', NOW()),
('dev025', 'im.elastic@email.com', '$2b$10$hashedpassword25', '임엘라스틱', '010-1234-0025', 'freelancer', 'active', 'Elasticsearch 검색 엔진 전문', '대전', NOW()),
('dev026', 'hwang.kafka@email.com', '$2b$10$hashedpassword26', '황카프카', '010-1234-0026', 'freelancer', 'active', 'Apache Kafka 메시징 시스템', '울산', NOW()),
('dev027', 'min.tensorflow@email.com', '$2b$10$hashedpassword27', '민텐서플로우', '010-1234-0027', 'freelancer', 'active', 'TensorFlow 딥러닝 모델 개발', '세종', NOW()),
('dev028', 'baek.pytorch@email.com', '$2b$10$hashedpassword28', '백파이토치', '010-1234-0028', 'freelancer', 'active', 'PyTorch 머신러닝 엔지니어', '서울', NOW()),
('dev029', 'ma.rust@email.com', '$2b$10$hashedpassword29', '마러스트', '010-1234-0029', 'freelancer', 'active', 'Rust 시스템 프로그래밍', '경기', NOW()),
('dev030', 'sa.golang@email.com', '$2b$10$hashedpassword30', '사고랭', '010-1234-0030', 'freelancer', 'active', 'Go 언어 마이크로서비스 개발', '부산', NOW()),
('dev031', 'ha.solidity@email.com', '$2b$10$hashedpassword31', '하솔리디티', '010-1234-0031', 'freelancer', 'active', 'Solidity 스마트 컨트랙트 개발', '대구', NOW()),
('dev032', 'na.react@email.com', '$2b$10$hashedpassword32', '나리액트', '010-1234-0032', 'freelancer', 'active', 'React 컴포넌트 라이브러리 제작', '인천', NOW()),
('dev033', 'ta.next@email.com', '$2b$10$hashedpassword33', '타넥스트', '010-1234-0033', 'freelancer', 'active', 'Next.js SSR/SSG 전문가', '광주', NOW()),
('dev034', 'ka.svelte@email.com', '$2b$10$hashedpassword34', '카스벨트', '010-1234-0034', 'freelancer', 'active', 'Svelte/SvelteKit 개발자', '대전', NOW()),
('dev035', 'la.ember@email.com', '$2b$10$hashedpassword35', '라엠버', '010-1234-0035', 'freelancer', 'active', 'Ember.js 프레임워크 전문', '울산', NOW()),
('dev036', 'pa.fastapi@email.com', '$2b$10$hashedpassword36', '파패스트에이피아이', '010-1234-0036', 'freelancer', 'active', 'FastAPI Python 백엔드 개발', '세종', NOW()),
('dev037', 'da.nestjs@email.com', '$2b$10$hashedpassword37', '다네스트', '010-1234-0037', 'freelancer', 'active', 'NestJS TypeScript 백엔드', '서울', NOW()),
('dev038', 'ra.django@email.com', '$2b$10$hashedpassword38', '라장고', '010-1234-0038', 'freelancer', 'active', 'Django REST Framework 전문', '경기', NOW()),
('dev039', 'ga.flask@email.com', '$2b$10$hashedpassword39', '가플라스크', '010-1234-0039', 'freelancer', 'active', 'Flask 마이크로 웹 프레임워크', '부산', NOW()),
('dev040', 'va.express@email.com', '$2b$10$hashedpassword40', '바익스프레스', '010-1234-0040', 'freelancer', 'active', 'Express.js 미들웨어 개발', '대구', NOW()),

-- 디자이너 (25명)
('design001', 'kim.ui@email.com', '$2b$10$hashedpassword41', '김유아이', '010-1234-0041', 'freelancer', 'active', 'UI/UX 디자인 전문가', '서울', NOW()),
('design002', 'lee.graphic@email.com', '$2b$10$hashedpassword42', '이그래픽', '010-1234-0042', 'freelancer', 'active', '그래픽 디자인 및 브랜딩 전문', '경기', NOW()),
('design003', 'park.web@email.com', '$2b$10$hashedpassword43', '박웹디자인', '010-1234-0043', 'freelancer', 'active', '웹 디자인 및 반응형 레이아웃', '부산', NOW()),
('design004', 'choi.mobile@email.com', '$2b$10$hashedpassword44', '최모바일디자인', '010-1234-0044', 'freelancer', 'active', '모바일 앱 UI/UX 디자인', '대구', NOW()),
('design005', 'jung.brand@email.com', '$2b$10$hashedpassword45', '정브랜드', '010-1234-0045', 'freelancer', 'active', '브랜드 아이덴티티 디자인', '인천', NOW()),
('design006', 'kang.motion@email.com', '$2b$10$hashedpassword46', '강모션', '010-1234-0046', 'freelancer', 'active', '모션 그래픽 및 애니메이션', '광주', NOW()),
('design007', 'yoon.3d@email.com', '$2b$10$hashedpassword47', '윤3디', '010-1234-0047', 'freelancer', 'active', '3D 모델링 및 렌더링', '대전', NOW()),
('design008', 'lim.illustration@email.com', '$2b$10$hashedpassword48', '임일러스트', '010-1234-0048', 'freelancer', 'active', '일러스트레이션 및 캐릭터 디자인', '울산', NOW()),
('design009', 'han.photo@email.com', '$2b$10$hashedpassword49', '한포토', '010-1234-0049', 'freelancer', 'active', '사진 편집 및 리터칭 전문', '세종', NOW()),
('design010', 'oh.video@email.com', '$2b$10$hashedpassword50', '오비디오', '010-1234-0050', 'freelancer', 'active', '영상 편집 및 후반 작업', '서울', NOW()),
('design011', 'shin.package@email.com', '$2b$10$hashedpassword51', '신패키지', '010-1234-0051', 'freelancer', 'active', '패키지 디자인 전문가', '경기', NOW()),
('design012', 'kwon.print@email.com', '$2b$10$hashedpassword52', '권프린트', '010-1234-0052', 'freelancer', 'active', '인쇄물 디자인 및 DTP', '부산', NOW()),
('design013', 'seo.logo@email.com', '$2b$10$hashedpassword53', '서로고', '010-1234-0053', 'freelancer', 'active', '로고 디자인 및 CI/VI', '대구', NOW()),
('design014', 'moon.interior@email.com', '$2b$10$hashedpassword54', '문인테리어', '010-1234-0054', 'freelancer', 'active', '인테리어 디자인 및 공간 설계', '인천', NOW()),
('design015', 'jang.fashion@email.com', '$2b$10$hashedpassword55', '장패션', '010-1234-0055', 'freelancer', 'active', '패션 디자인 및 의류 제작', '광주', NOW()),
('design016', 'song.game@email.com', '$2b$10$hashedpassword56', '송게임', '010-1234-0056', 'freelancer', 'active', '게임 UI/UX 디자인', '대전', NOW()),
('design017', 'go.prototype@email.com', '$2b$10$hashedpassword57', '고프로토타입', '010-1234-0057', 'freelancer', 'active', '프로토타이핑 및 와이어프레임', '울산', NOW()),
('design018', 'nam.figma@email.com', '$2b$10$hashedpassword58', '남피그마', '010-1234-0058', 'freelancer', 'active', 'Figma 디자인 시스템 구축', '세종', NOW()),
('design019', 'woo.sketch@email.com', '$2b$10$hashedpassword59', '우스케치', '010-1234-0059', 'freelancer', 'active', 'Sketch 디자인 툴 전문가', '서울', NOW()),
('design020', 'ryu.adobe@email.com', '$2b$10$hashedpassword60', '류어도비', '010-1234-0060', 'freelancer', 'active', 'Adobe Creative Suite 마스터', '경기', NOW()),
('design021', 'hong.ux@email.com', '$2b$10$hashedpassword61', '홍유엑스', '010-1234-0061', 'freelancer', 'active', 'UX 리서치 및 사용성 테스트', '부산', NOW()),
('design022', 'cho.visual@email.com', '$2b$10$hashedpassword62', '조비주얼', '010-1234-0062', 'freelancer', 'active', '비주얼 디자인 및 타이포그래피', '대구', NOW()),
('design023', 'ahn.interaction@email.com', '$2b$10$hashedpassword63', '안인터랙션', '010-1234-0063', 'freelancer', 'active', '인터랙션 디자인 전문가', '인천', NOW()),
('design024', 'yoo.service@email.com', '$2b$10$hashedpassword64', '유서비스', '010-1234-0064', 'freelancer', 'active', '서비스 디자인 및 고객 경험', '광주', NOW()),
('design025', 'im.product@email.com', '$2b$10$hashedpassword65', '임프로덕트', '010-1234-0065', 'freelancer', 'active', '프로덕트 디자인 전문가', '대전', NOW()),

-- 기획자 및 PM (20명)
('pm001', 'kim.pm@email.com', '$2b$10$hashedpassword66', '김피엠', '010-1234-0066', 'freelancer', 'active', 'IT 프로젝트 관리 전문가', '서울', NOW()),
('pm002', 'lee.plan@email.com', '$2b$10$hashedpassword67', '이기획', '010-1234-0067', 'freelancer', 'active', '서비스 기획 및 BM 설계', '경기', NOW()),
('pm003', 'park.po@email.com', '$2b$10$hashedpassword68', '박프로덕트오너', '010-1234-0068', 'freelancer', 'active', 'Product Owner 및 백로그 관리', '부산', NOW()),
('pm004', 'choi.ba@email.com', '$2b$10$hashedpassword69', '최비에이', '010-1234-0069', 'freelancer', 'active', 'Business Analyst 및 요구사항 분석', '대구', NOW()),
('pm005', 'jung.scrum@email.com', '$2b$10$hashedpassword70', '정스크럼', '010-1234-0070', 'freelancer', 'active', 'Scrum Master 및 애자일 코치', '인천', NOW()),
('pm006', 'kang.strategy@email.com', '$2b$10$hashedpassword71', '강전략', '010-1234-0071', 'freelancer', 'active', '전략 기획 및 시장 분석', '광주', NOW()),
('pm007', 'yoon.data@email.com', '$2b$10$hashedpassword72', '윤데이터', '010-1234-0072', 'freelancer', 'active', '데이터 분석 및 BI 기획', '대전', NOW()),
('pm008', 'lim.operation@email.com', '$2b$10$hashedpassword73', '임오퍼레이션', '010-1234-0073', 'freelancer', 'active', '운영 기획 및 프로세스 개선', '울산', NOW()),
('pm009', 'han.marketing@email.com', '$2b$10$hashedpassword74', '한마케팅', '010-1234-0074', 'freelancer', 'active', '마케팅 기획 및 캠페인 관리', '세종', NOW()),
('pm010', 'oh.content@email.com', '$2b$10$hashedpassword75', '오콘텐츠', '010-1234-0075', 'freelancer', 'active', '콘텐츠 기획 및 에디터', '서울', NOW()),
('pm011', 'shin.event@email.com', '$2b$10$hashedpassword76', '신이벤트', '010-1234-0076', 'freelancer', 'active', '이벤트 기획 및 프로모션', '경기', NOW()),
('pm012', 'kwon.digital@email.com', '$2b$10$hashedpassword77', '권디지털', '010-1234-0077', 'freelancer', 'active', '디지털 트랜스포메이션 기획', '부산', NOW()),
('pm013', 'seo.mobile@email.com', '$2b$10$hashedpassword78', '서모바일', '010-1234-0078', 'freelancer', 'active', '모바일 서비스 기획자', '대구', NOW()),
('pm014', 'moon.ecommerce@email.com', '$2b$10$hashedpassword79', '문이커머스', '010-1234-0079', 'freelancer', 'active', '이커머스 기획 및 운영', '인천', NOW()),
('pm015', 'jang.startup@email.com', '$2b$10$hashedpassword80', '장스타트업', '010-1234-0080', 'freelancer', 'active', '스타트업 사업 기획', '광주', NOW()),
('pm016', 'song.innovation@email.com', '$2b$10$hashedpassword81', '송혁신', '010-1234-0081', 'freelancer', 'active', '혁신 기획 및 신사업 개발', '대전', NOW()),
('pm017', 'go.consulting@email.com', '$2b$10$hashedpassword82', '고컨설팅', '010-1234-0082', 'freelancer', 'active', 'IT 컨설팅 및 솔루션 기획', '울산', NOW()),
('pm018', 'nam.growth@email.com', '$2b$10$hashedpassword83', '남그로스', '010-1234-0083', 'freelancer', 'active', '그로스 해킹 및 성장 전략', '세종', NOW()),
('pm019', 'woo.platform@email.com', '$2b$10$hashedpassword84', '우플랫폼', '010-1234-0084', 'freelancer', 'active', '플랫폼 비즈니스 기획', '서울', NOW()),
('pm020', 'ryu.partnership@email.com', '$2b$10$hashedpassword85', '류파트너십', '010-1234-0085', 'freelancer', 'active', '파트너십 및 제휴 기획', '경기', NOW()),

-- 마케터 및 기타 전문가 (15명)
('market001', 'kim.seo@email.com', '$2b$10$hashedpassword86', '김에스이오', '010-1234-0086', 'freelancer', 'active', 'SEO 및 검색엔진 마케팅 전문', '서울', NOW()),
('market002', 'lee.sns@email.com', '$2b$10$hashedpassword87', '이에스엔에스', '010-1234-0087', 'freelancer', 'active', 'SNS 마케팅 및 인플루언서', '경기', NOW()),
('market003', 'park.performance@email.com', '$2b$10$hashedpassword88', '박퍼포먼스', '010-1234-0088', 'freelancer', 'active', '퍼포먼스 마케팅 및 광고 운영', '부산', NOW()),
('market004', 'choi.brand@email.com', '$2b$10$hashedpassword89', '최브랜드', '010-1234-0089', 'freelancer', 'active', '브랜드 마케팅 및 PR', '대구', NOW()),
('market005', 'jung.copy@email.com', '$2b$10$hashedpassword90', '정카피', '010-1234-0090', 'freelancer', 'active', '카피라이팅 및 콘텐츠 라이팅', '인천', NOW()),
('writer001', 'kang.tech@email.com', '$2b$10$hashedpassword91', '강테크라이터', '010-1234-0091', 'freelancer', 'active', '기술 문서 작성 및 매뉴얼 제작', '광주', NOW()),
('writer002', 'yoon.blog@email.com', '$2b$10$hashedpassword92', '윤블로그', '010-1234-0092', 'freelancer', 'active', '블로그 운영 및 콘텐츠 제작', '대전', NOW()),
('trans001', 'lim.english@email.com', '$2b$10$hashedpassword93', '임영어', '010-1234-0093', 'freelancer', 'active', '영어 번역 및 통역 전문', '울산', NOW()),
('trans002', 'han.japanese@email.com', '$2b$10$hashedpassword94', '한일어', '010-1234-0094', 'freelancer', 'active', '일본어 번역 및 로컬라이징', '세종', NOW()),
('consult001', 'oh.finance@email.com', '$2b$10$hashedpassword95', '오파이낸스', '010-1234-0095', 'freelancer', 'active', '재무 컨설팅 및 투자 분석', '서울', NOW()),
('consult002', 'shin.hr@email.com', '$2b$10$hashedpassword96', '신에이치알', '010-1234-0096', 'freelancer', 'active', '인사 컨설팅 및 조직 개발', '경기', NOW()),
('consult003', 'kwon.legal@email.com', '$2b$10$hashedpassword97', '권법무', '010-1234-0097', 'freelancer', 'active', '법무 컨설팅 및 계약서 검토', '부산', NOW()),
('edu001', 'seo.training@email.com', '$2b$10$hashedpassword98', '서트레이닝', '010-1234-0098', 'freelancer', 'active', 'IT 교육 및 강의 전문가', '대구', NOW()),
('edu002', 'moon.mentor@email.com', '$2b$10$hashedpassword99', '문멘토', '010-1234-0099', 'freelancer', 'active', '멘토링 및 커리어 코칭', '인천', NOW()),
('analyst001', 'jang.data@email.com', '$2b$10$hashedpassword100', '장데이터분석가', '010-1234-0100', 'freelancer', 'active', '빅데이터 분석 및 시각화 전문', '광주', NOW());

-- Insert 100 Freelancers data
INSERT INTO freelancers (user_id, title, description, skills, experience_years, experience_level, hourly_rate, availability, preferred_work_type, portfolio_url, github_url, linkedin_url, rating, total_reviews, completed_projects, is_verified, created_at) VALUES
-- 개발자 프리랜서 (40명)
(1, 'React/TypeScript 프론트엔드 전문가', 'React와 TypeScript를 활용한 현대적인 웹 애플리케이션 개발 전문가입니다. Next.js, Tailwind CSS, Redux Toolkit 등 최신 기술 스택에 능숙합니다.', '["React", "TypeScript", "Next.js", "Tailwind CSS", "Redux"]', 5, 'senior', 80000.00, 'available', 'hybrid', 'https://portfolio.kimfrontend.com', 'https://github.com/kimfrontend', 'https://linkedin.com/in/kimfrontend', 4.8, 25, 40, TRUE, NOW()),
(2, 'Node.js/Spring Boot 백엔드 개발자', 'Node.js와 Spring Boot를 활용한 RESTful API 및 마이크로서비스 아키텍처 설계 전문가입니다.', '["Node.js", "Spring Boot", "PostgreSQL", "Redis", "Docker"]', 7, 'expert', 90000.00, 'available', 'remote', 'https://portfolio.leebackend.com', 'https://github.com/leebackend', 'https://linkedin.com/in/leebackend', 4.9, 30, 55, TRUE, NOW()),
(3, 'MERN 풀스택 개발자', 'MongoDB, Express, React, Node.js를 활용한 풀스택 웹 애플리케이션 개발 전문가입니다.', '["React", "Node.js", "MongoDB", "Express", "AWS"]', 4, 'mid', 70000.00, 'available', 'all', 'https://portfolio.parkfullstack.com', 'https://github.com/parkfullstack', 'https://linkedin.com/in/parkfullstack', 4.7, 20, 32, TRUE, NOW()),
(4, 'React Native/Flutter 모바일 개발자', 'React Native와 Flutter를 활용한 크로스플랫폼 모바일 앱 개발 전문가입니다.', '["React Native", "Flutter", "Dart", "Firebase", "iOS", "Android"]', 6, 'senior', 85000.00, 'available', 'remote', 'https://portfolio.choimobile.com', 'https://github.com/choimobile', 'https://linkedin.com/in/choimobile', 4.8, 22, 38, TRUE, NOW()),
(5, 'Python/Django 웹 개발자', 'Python과 Django를 활용한 웹 애플리케이션 및 데이터 처리 시스템 개발 전문가입니다.', '["Python", "Django", "PostgreSQL", "Celery", "Redis"]', 5, 'senior', 75000.00, 'available', 'hybrid', 'https://portfolio.jungpython.com', 'https://github.com/jungpython', 'https://linkedin.com/in/jungpython', 4.6, 18, 35, TRUE, NOW()),
(6, 'Java Spring 엔터프라이즈 개발자', 'Java Spring 기반의 대규모 엔터프라이즈 시스템 개발 및 설계 전문가입니다.', '["Java", "Spring", "Spring Boot", "MyBatis", "Oracle", "Maven"]', 8, 'expert', 95000.00, 'available', 'onsite', 'https://portfolio.kangjava.com', 'https://github.com/kangjava', 'https://linkedin.com/in/kangjava', 4.9, 35, 60, TRUE, NOW()),
(7, 'React 생태계 전문가', 'React 생태계의 모든 도구와 라이브러리에 능숙한 프론트엔드 전문가입니다.', '["React", "React Hook", "Context API", "React Router", "Jest"]', 4, 'mid', 72000.00, 'available', 'remote', 'https://portfolio.yoonreact.com', 'https://github.com/yoonreact', 'https://linkedin.com/in/yoonreact', 4.7, 16, 28, FALSE, NOW()),
(8, 'Vue.js/Nuxt.js 개발자', 'Vue.js와 Nuxt.js를 활용한 SPA 및 SSR 웹 애플리케이션 개발 전문가입니다.', '["Vue.js", "Nuxt.js", "Vuex", "Vue Router", "Axios"]', 3, 'mid', 68000.00, 'available', 'hybrid', 'https://portfolio.limvue.com', 'https://github.com/limvue', 'https://linkedin.com/in/limvue', 4.5, 14, 25, FALSE, NOW()),
(9, 'Angular 프레임워크 전문가', 'Angular 프레임워크를 활용한 대규모 웹 애플리케이션 개발 전문가입니다.', '["Angular", "TypeScript", "RxJS", "NgRx", "Angular Material"]', 6, 'senior', 82000.00, 'available', 'onsite', 'https://portfolio.hanangular.com', 'https://github.com/hanangular', 'https://linkedin.com/in/hanangular', 4.8, 21, 36, TRUE, NOW()),
(10, 'Node.js 백엔드 및 API 개발자', 'Node.js를 활용한 RESTful API 및 GraphQL 서버 개발 전문가입니다.', '["Node.js", "Express", "GraphQL", "MongoDB", "JWT"]', 5, 'senior', 78000.00, 'available', 'remote', 'https://portfolio.ohnodejs.com', 'https://github.com/ohnodejs', 'https://linkedin.com/in/ohnodejs', 4.7, 19, 33, TRUE, NOW()),
(11, 'AWS 클라우드 및 DevOps 전문가', 'AWS 클라우드 인프라 구축 및 CI/CD 파이프라인 설계 전문가입니다.', '["AWS", "Docker", "Kubernetes", "Jenkins", "Terraform"]', 7, 'expert', 100000.00, 'available', 'all', 'https://portfolio.shindevops.com', 'https://github.com/shindevops', 'https://linkedin.com/in/shindevops', 4.9, 28, 45, TRUE, NOW()),
(12, '데이터베이스 설계 및 최적화 전문가', 'MySQL, PostgreSQL, MongoDB 등 다양한 데이터베이스 설계 및 최적화 전문가입니다.', '["MySQL", "PostgreSQL", "MongoDB", "Redis", "Database Design"]', 6, 'senior', 85000.00, 'available', 'hybrid', 'https://portfolio.kwondb.com', 'https://github.com/kwondb', 'https://linkedin.com/in/kwondb', 4.8, 24, 41, TRUE, NOW()),
(13, 'AI/ML 모델 개발 및 데이터 분석가', 'TensorFlow, PyTorch를 활용한 머신러닝 모델 개발 및 데이터 분석 전문가입니다.', '["Python", "TensorFlow", "PyTorch", "Pandas", "Scikit-learn"]', 4, 'mid', 88000.00, 'available', 'remote', 'https://portfolio.seoai.com', 'https://github.com/seoai', 'https://linkedin.com/in/seoai', 4.6, 15, 27, TRUE, NOW()),
(14, '블록체인 DApp 개발자', 'Solidity를 활용한 스마트 컨트랙트 및 DApp 개발 전문가입니다.', '["Solidity", "Web3.js", "Ethereum", "Truffle", "Hardhat"]', 3, 'mid', 92000.00, 'available', 'remote', 'https://portfolio.moonblockchain.com', 'https://github.com/moonblockchain', 'https://linkedin.com/in/moonblockchain', 4.5, 12, 22, FALSE, NOW()),
(15, '보안 및 해킹 방어 전문가', '웹 애플리케이션 보안 취약점 분석 및 보안 솔루션 개발 전문가입니다.', '["Cybersecurity", "Penetration Testing", "OWASP", "Security Audit", "Encryption"]', 8, 'expert', 110000.00, 'available', 'onsite', 'https://portfolio.jangsecurity.com', 'https://github.com/jangsecurity', 'https://linkedin.com/in/jangsecurity', 4.9, 32, 48, TRUE, NOW()),
(16, 'Unity 게임 개발자', 'Unity 엔진을 활용한 2D/3D 게임 개발 및 AR/VR 콘텐츠 제작 전문가입니다.', '["Unity", "C#", "AR", "VR", "Game Development"]', 5, 'senior', 75000.00, 'available', 'hybrid', 'https://portfolio.songunity.com', 'https://github.com/songunity', 'https://linkedin.com/in/songunity', 4.7, 17, 29, TRUE, NOW()),
(17, 'Flutter 크로스플랫폼 개발자', 'Flutter를 활용한 iOS/Android 앱 개발 및 웹 애플리케이션 개발 전문가입니다.', '["Flutter", "Dart", "Firebase", "SQLite", "Provider"]', 3, 'mid', 70000.00, 'available', 'remote', 'https://portfolio.goflutter.com', 'https://github.com/goflutter', 'https://linkedin.com/in/goflutter', 4.6, 13, 24, FALSE, NOW()),
(18, 'iOS Swift 네이티브 앱 개발자', 'Swift를 활용한 iOS 네이티브 앱 개발 및 App Store 배포 전문가입니다.', '["Swift", "iOS", "SwiftUI", "Core Data", "CloudKit"]', 6, 'senior', 90000.00, 'available', 'hybrid', 'https://portfolio.namswift.com', 'https://github.com/namswift', 'https://linkedin.com/in/namswift', 4.8, 26, 42, TRUE, NOW()),
(19, 'Android Kotlin 개발자', 'Kotlin을 활용한 Android 네이티브 앱 개발 및 Google Play 배포 전문가입니다.', '["Kotlin", "Android", "Jetpack Compose", "Room", "Retrofit"]', 4, 'mid', 72000.00, 'busy', 'onsite', 'https://portfolio.wookotlin.com', 'https://github.com/wookotlin', 'https://linkedin.com/in/wookotlin', 4.7, 18, 30, TRUE, NOW()),
(20, 'PHP Laravel 웹 개발자', 'PHP Laravel 프레임워크를 활용한 웹 애플리케이션 개발 전문가입니다.', '["PHP", "Laravel", "MySQL", "Composer", "Blade"]', 5, 'senior', 65000.00, 'available', 'all', 'https://portfolio.ryuphp.com', 'https://github.com/ryuphp', 'https://linkedin.com/in/ryuphp', 4.6, 16, 28, FALSE, NOW()),
(21, 'Docker 컨테이너 및 쿠버네티스 전문가', 'Docker와 Kubernetes를 활용한 컨테이너 오케스트레이션 전문가입니다.', '["Docker", "Kubernetes", "Helm", "Istio", "Monitoring"]', 6, 'senior', 95000.00, 'available', 'remote', 'https://portfolio.hongdocker.com', 'https://github.com/hongdocker', 'https://linkedin.com/in/hongdocker', 4.8, 23, 39, TRUE, NOW()),
(22, 'GraphQL API 설계 전문가', 'GraphQL을 활용한 효율적인 API 설계 및 개발 전문가입니다.', '["GraphQL", "Apollo", "Prisma", "Node.js", "React"]', 4, 'mid', 78000.00, 'available', 'hybrid', 'https://portfolio.chographql.com', 'https://github.com/chographql', 'https://linkedin.com/in/chographql', 4.7, 15, 26, TRUE, NOW()),
(23, 'MongoDB 및 NoSQL 데이터베이스 전문가', 'MongoDB를 비롯한 NoSQL 데이터베이스 설계 및 최적화 전문가입니다.', '["MongoDB", "Mongoose", "Aggregation", "Sharding", "Replica Set"]', 5, 'senior', 80000.00, 'available', 'remote', 'https://portfolio.ahnmongodb.com', 'https://github.com/ahnmongodb', 'https://linkedin.com/in/ahnmongodb', 4.6, 19, 34, TRUE, NOW()),
(24, 'Redis 캐싱 및 성능 최적화 전문가', 'Redis를 활용한 캐싱 전략 및 성능 최적화 전문가입니다.', '["Redis", "Caching", "Performance", "Load Balancing", "Database Optimization"]', 6, 'senior', 85000.00, 'available', 'all', 'https://portfolio.yooredis.com', 'https://github.com/yooredis', 'https://linkedin.com/in/yooredis', 4.8, 21, 37, TRUE, NOW()),
(25, 'Elasticsearch 검색 엔진 전문가', 'Elasticsearch를 활용한 검색 시스템 구축 및 최적화 전문가입니다.', '["Elasticsearch", "Kibana", "Logstash", "Search Engine", "Data Visualization"]', 4, 'mid', 82000.00, 'available', 'hybrid', 'https://portfolio.imelastic.com', 'https://github.com/imelastic', 'https://linkedin.com/in/imelastic', 4.7, 14, 25, FALSE, NOW()),
(26, 'Apache Kafka 메시징 시스템 전문가', 'Apache Kafka를 활용한 실시간 데이터 스트리밍 시스템 구축 전문가입니다.', '["Apache Kafka", "Zookeeper", "Streaming", "Event Driven", "Microservices"]', 5, 'senior', 88000.00, 'available', 'remote', 'https://portfolio.hwangkafka.com', 'https://github.com/hwangkafka', 'https://linkedin.com/in/hwangkafka', 4.8, 17, 31, TRUE, NOW()),
(27, 'TensorFlow 딥러닝 모델 개발자', 'TensorFlow를 활용한 딥러닝 모델 개발 및 배포 전문가입니다.', '["TensorFlow", "Keras", "Deep Learning", "CNN", "RNN"]', 3, 'mid', 90000.00, 'available', 'remote', 'https://portfolio.mintensorflow.com', 'https://github.com/mintensorflow', 'https://linkedin.com/in/mintensorflow', 4.6, 12, 21, TRUE, NOW()),
(28, 'PyTorch 머신러닝 엔지니어', 'PyTorch를 활용한 머신러닝 모델 개발 및 연구 전문가입니다.', '["PyTorch", "Machine Learning", "Computer Vision", "NLP", "MLOps"]', 4, 'mid', 85000.00, 'available', 'hybrid', 'https://portfolio.baekpytorch.com', 'https://github.com/baekpytorch', 'https://linkedin.com/in/baekpytorch', 4.7, 13, 23, TRUE, NOW()),
(29, 'Rust 시스템 프로그래밍 전문가', 'Rust를 활용한 시스템 프로그래밍 및 고성능 애플리케이션 개발 전문가입니다.', '["Rust", "System Programming", "WebAssembly", "Actix", "Tokio"]', 5, 'senior', 95000.00, 'available', 'remote', 'https://portfolio.marust.com', 'https://github.com/marust', 'https://linkedin.com/in/marust', 4.8, 16, 28, TRUE, NOW()),
(30, 'Go 언어 마이크로서비스 개발자', 'Go 언어를 활용한 마이크로서비스 아키텍처 설계 및 개발 전문가입니다.', '["Go", "Microservices", "gRPC", "Gin", "Docker"]', 4, 'mid', 80000.00, 'available', 'all', 'https://portfolio.sagolang.com', 'https://github.com/sagolang', 'https://linkedin.com/in/sagolang', 4.7, 15, 27, TRUE, NOW()),
(31, 'Solidity 스마트 컨트랙트 개발자', 'Solidity를 활용한 스마트 컨트랙트 개발 및 DeFi 프로토콜 구축 전문가입니다.', '["Solidity", "Smart Contract", "DeFi", "Web3", "Ethereum"]', 3, 'mid', 100000.00, 'available', 'remote', 'https://portfolio.hasolidity.com', 'https://github.com/hasolidity', 'https://linkedin.com/in/hasolidity', 4.6, 11, 19, FALSE, NOW()),
(32, 'React 컴포넌트 라이브러리 제작자', 'React 컴포넌트 라이브러리 제작 및 디자인 시스템 구축 전문가입니다.', '["React", "Component Library", "Storybook", "Design System", "npm"]', 5, 'senior', 82000.00, 'available', 'hybrid', 'https://portfolio.nareact.com', 'https://github.com/nareact', 'https://linkedin.com/in/nareact', 4.8, 20, 35, TRUE, NOW()),
(33, 'Next.js SSR/SSG 전문가', 'Next.js를 활용한 서버사이드 렌더링 및 정적 사이트 생성 전문가입니다.', '["Next.js", "SSR", "SSG", "Vercel", "SEO"]', 4, 'mid', 75000.00, 'available', 'remote', 'https://portfolio.tanext.com', 'https://github.com/tanext', 'https://linkedin.com/in/tanext', 4.7, 18, 30, TRUE, NOW()),
(34, 'Svelte/SvelteKit 개발자', 'Svelte와 SvelteKit을 활용한 경량 웹 애플리케이션 개발 전문가입니다.', '["Svelte", "SvelteKit", "Vite", "JavaScript", "CSS"]', 3, 'mid', 70000.00, 'available', 'all', 'https://portfolio.kasvelte.com', 'https://github.com/kasvelte', 'https://linkedin.com/in/kasvelte', 4.5, 12, 22, FALSE, NOW()),
(35, 'Ember.js 프레임워크 전문가', 'Ember.js 프레임워크를 활용한 대규모 웹 애플리케이션 개발 전문가입니다.', '["Ember.js", "Handlebars", "Ember CLI", "Ember Data", "JavaScript"]', 6, 'senior', 78000.00, 'available', 'onsite', 'https://portfolio.laember.com', 'https://github.com/laember', 'https://linkedin.com/in/laember', 4.6, 14, 26, FALSE, NOW()),
(36, 'FastAPI Python 백엔드 개발자', 'FastAPI를 활용한 고성능 Python 백엔드 API 개발 전문가입니다.', '["Python", "FastAPI", "Pydantic", "SQLAlchemy", "PostgreSQL"]', 4, 'mid', 75000.00, 'available', 'hybrid', 'https://portfolio.pafastapi.com', 'https://github.com/pafastapi', 'https://linkedin.com/in/pafastapi', 4.7, 16, 28, TRUE, NOW()),
(37, 'NestJS TypeScript 백엔드 개발자', 'NestJS를 활용한 TypeScript 기반 백엔드 API 개발 전문가입니다.', '["NestJS", "TypeScript", "TypeORM", "PostgreSQL", "Swagger"]', 3, 'mid', 78000.00, 'available', 'remote', 'https://portfolio.danestjs.com', 'https://github.com/danestjs', 'https://linkedin.com/in/danestjs', 4.6, 13, 24, TRUE, NOW()),
(38, 'Django REST Framework 전문가', 'Django REST Framework를 활용한 RESTful API 개발 및 백엔드 시스템 구축 전문가입니다.', '["Django", "DRF", "Python", "PostgreSQL", "Celery"]', 5, 'senior', 72000.00, 'available', 'all', 'https://portfolio.radjango.com', 'https://github.com/radjango', 'https://linkedin.com/in/radjango', 4.7, 19, 33, TRUE, NOW()),
(39, 'Flask 마이크로 웹 프레임워크 전문가', 'Flask를 활용한 경량 웹 애플리케이션 및 API 개발 전문가입니다.', '["Flask", "Python", "SQLAlchemy", "Jinja2", "Gunicorn"]', 4, 'mid', 68000.00, 'available', 'hybrid', 'https://portfolio.gaflask.com', 'https://github.com/gaflask', 'https://linkedin.com/in/gaflask', 4.5, 15, 26, FALSE, NOW()),
(40, 'Express.js 미들웨어 개발자', 'Express.js를 활용한 Node.js 백엔드 및 미들웨어 개발 전문가입니다.', '["Express.js", "Node.js", "Middleware", "JWT", "MongoDB"]', 5, 'senior', 74000.00, 'available', 'remote', 'https://portfolio.vaexpress.com', 'https://github.com/vaexpress', 'https://linkedin.com/in/vaexpress', 4.6, 17, 29, TRUE, NOW()),

-- 디자이너 프리랜서 (25명)
(41, 'UI/UX 디자인 전문가', '사용자 중심의 UI/UX 디자인으로 직관적이고 매력적인 디지털 경험을 만들어갑니다. Figma, Sketch, Adobe XD 전문.', '["UI Design", "UX Design", "Figma", "Sketch", "Adobe XD", "Prototyping"]', 4, 'mid', 60000.00, 'available', 'hybrid', 'https://portfolio.kimui.com', NULL, 'https://linkedin.com/in/kimui', 4.7, 22, 38, TRUE, NOW()),
(42, '그래픽 디자인 및 브랜딩 전문가', '브랜드 아이덴티티부터 마케팅 콜래터럴까지 일관된 시각적 언어로 브랜드 가치를 전달합니다.', '["Graphic Design", "Branding", "Adobe Illustrator", "Adobe Photoshop", "Logo Design"]', 6, 'senior', 65000.00, 'available', 'all', 'https://portfolio.leegraphic.com', NULL, 'https://linkedin.com/in/leegraphic', 4.8, 28, 45, TRUE, NOW()),
(43, '웹 디자인 및 반응형 레이아웃 전문가', '다양한 디바이스에서 최적화된 웹 디자인과 사용자 경험을 제공합니다.', '["Web Design", "Responsive Design", "HTML/CSS", "Figma", "Adobe XD"]', 5, 'senior', 58000.00, 'available', 'remote', 'https://portfolio.parkweb.com', NULL, 'https://linkedin.com/in/parkweb', 4.6, 20, 35, TRUE, NOW()),
(44, '모바일 앱 UI/UX 디자인 전문가', 'iOS와 Android 플랫폼에 최적화된 모바일 앱 인터페이스 디자인 전문가입니다.', '["Mobile Design", "iOS Design", "Android Design", "Material Design", "Human Interface Guidelines"]', 4, 'mid', 62000.00, 'available', 'hybrid', 'https://portfolio.choimobiledesign.com', NULL, 'https://linkedin.com/in/choimobiledesign', 4.7, 18, 32, TRUE, NOW()),
(45, '브랜드 아이덴티티 디자인 전문가', '브랜드의 핵심 가치를 시각적으로 표현하는 로고, CI/VI 시스템 구축 전문가입니다.', '["Brand Identity", "Logo Design", "CI/VI", "Adobe Illustrator", "Brand Guidelines"]', 7, 'expert', 70000.00, 'available', 'onsite', 'https://portfolio.jungbrand.com', NULL, 'https://linkedin.com/in/jungbrand', 4.9, 32, 52, TRUE, NOW()),
(46, '모션 그래픽 및 애니메이션 전문가', 'After Effects를 활용한 모션 그래픽, 애니메이션, 영상 콘텐츠 제작 전문가입니다.', '["Motion Graphics", "After Effects", "Cinema 4D", "Animation", "Video Editing"]', 5, 'senior', 75000.00, 'available', 'remote', 'https://portfolio.kangmotion.com', NULL, 'https://linkedin.com/in/kangmotion', 4.8, 25, 40, TRUE, NOW()),
(47, '3D 모델링 및 렌더링 전문가', '3ds Max, Maya, Blender를 활용한 3D 모델링, 렌더링, 애니메이션 제작 전문가입니다.', '["3D Modeling", "3ds Max", "Maya", "Blender", "V-Ray", "Rendering"]', 6, 'senior', 80000.00, 'available', 'hybrid', 'https://portfolio.yoon3d.com', NULL, 'https://linkedin.com/in/yoon3d', 4.7, 21, 36, TRUE, NOW()),
(48, '일러스트레이션 및 캐릭터 디자인 전문가', '독창적인 일러스트레이션과 매력적인 캐릭터 디자인으로 스토리텔링을 시각화합니다.', '["Illustration", "Character Design", "Digital Art", "Procreate", "Adobe Illustrator"]', 4, 'mid', 55000.00, 'available', 'all', 'https://portfolio.limillust.com', NULL, 'https://linkedin.com/in/limillust', 4.6, 19, 33, FALSE, NOW()),
(49, '사진 편집 및 리터칭 전문가', 'Adobe Photoshop을 활용한 전문적인 사진 편집, 리터칭, 합성 작업 전문가입니다.', '["Photo Editing", "Retouching", "Adobe Photoshop", "Color Grading", "Digital Imaging"]', 5, 'senior', 50000.00, 'available', 'remote', 'https://portfolio.hanphoto.com', NULL, 'https://linkedin.com/in/hanphoto', 4.5, 16, 28, FALSE, NOW()),
(50, '영상 편집 및 후반 작업 전문가', 'Premiere Pro, DaVinci Resolve를 활용한 영상 편집, 컬러 그레이딩, 사운드 디자인 전문가입니다.', '["Video Editing", "Premiere Pro", "DaVinci Resolve", "Color Grading", "Sound Design"]', 6, 'senior', 70000.00, 'available', 'hybrid', 'https://portfolio.ohvideo.com', NULL, 'https://linkedin.com/in/ohvideo', 4.8, 24, 41, TRUE, NOW()),
(51, '패키지 디자인 전문가', '제품의 가치를 극대화하는 창의적이고 기능적인 패키지 디자인 전문가입니다.', '["Package Design", "Product Design", "Adobe Illustrator", "3D Visualization", "Printing"]', 5, 'senior', 58000.00, 'available', 'onsite', 'https://portfolio.shinpackage.com', NULL, 'https://linkedin.com/in/shinpackage', 4.6, 17, 30, TRUE, NOW()),
(52, '인쇄물 디자인 및 DTP 전문가', '브로슈어, 카탈로그, 포스터 등 다양한 인쇄물 디자인 및 프리프레스 작업 전문가입니다.', '["Print Design", "DTP", "InDesign", "Prepress", "Typography"]', 7, 'expert', 52000.00, 'available', 'all', 'https://portfolio.kwonprint.com', NULL, 'https://linkedin.com/in/kwonprint', 4.7, 26, 44, TRUE, NOW()),
(53, '로고 디자인 및 CI/VI 전문가', '브랜드의 정체성을 담은 로고 디자인과 체계적인 CI/VI 시스템 구축 전문가입니다.', '["Logo Design", "CI/VI", "Brand Identity", "Adobe Illustrator", "Brand Guidelines"]', 4, 'mid', 60000.00, 'available', 'hybrid', 'https://portfolio.seologo.com', NULL, 'https://linkedin.com/in/seologo', 4.5, 15, 27, FALSE, NOW()),
(54, '인테리어 디자인 및 공간 설계 전문가', 'AutoCAD, SketchUp을 활용한 인테리어 디자인 및 3D 공간 시각화 전문가입니다.', '["Interior Design", "AutoCAD", "SketchUp", "3D Visualization", "Space Planning"]', 6, 'senior', 65000.00, 'available', 'onsite', 'https://portfolio.mooninterior.com', NULL, 'https://linkedin.com/in/mooninterior', 4.8, 22, 37, TRUE, NOW()),
(55, '패션 디자인 및 의류 제작 전문가', '트렌드를 반영한 패션 디자인과 패턴 제작, 의류 생산 관리 전문가입니다.', '["Fashion Design", "Pattern Making", "Textile Design", "CAD", "Fashion Illustration"]', 5, 'senior', 55000.00, 'available', 'all', 'https://portfolio.jangfashion.com', NULL, 'https://linkedin.com/in/jangfashion', 4.6, 18, 31, FALSE, NOW()),
(56, '게임 UI/UX 디자인 전문가', '모바일 게임과 PC 게임의 사용자 인터페이스 및 경험 디자인 전문가입니다.', '["Game UI", "Game UX", "Unity UI", "Mobile Game Design", "Icon Design"]', 4, 'mid', 68000.00, 'available', 'remote', 'https://portfolio.songgame.com', NULL, 'https://linkedin.com/in/songgame', 4.7, 20, 34, TRUE, NOW()),
(57, '프로토타이핑 및 와이어프레임 전문가', '사용자 경험 설계를 위한 프로토타이핑과 와이어프레임 제작 전문가입니다.', '["Prototyping", "Wireframing", "Figma", "Sketch", "InVision", "User Journey"]', 3, 'mid', 58000.00, 'available', 'hybrid', 'https://portfolio.goprototype.com', NULL, 'https://linkedin.com/in/goprototype', 4.5, 14, 25, FALSE, NOW()),
(58, 'Figma 디자인 시스템 구축 전문가', 'Figma를 활용한 체계적인 디자인 시스템 구축 및 컴포넌트 라이브러리 제작 전문가입니다.', '["Figma", "Design System", "Component Library", "Auto Layout", "Design Tokens"]', 4, 'mid', 65000.00, 'available', 'remote', 'https://portfolio.namfigma.com', NULL, 'https://linkedin.com/in/namfigma', 4.8, 21, 36, TRUE, NOW()),
(59, 'Sketch 디자인 툴 전문가', 'Sketch를 활용한 디지털 제품 디자인 및 프로토타이핑 전문가입니다.', '["Sketch", "Symbol", "Craft", "InVision", "Principle"]', 5, 'senior', 62000.00, 'available', 'all', 'https://portfolio.woosketch.com', NULL, 'https://linkedin.com/in/woosketch', 4.6, 17, 29, FALSE, NOW()),
(60, 'Adobe Creative Suite 마스터', 'Adobe 전체 제품군을 활용한 종합적인 디자인 솔루션 제공 전문가입니다.', '["Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign", "Adobe After Effects", "Adobe XD"]', 8, 'expert', 75000.00, 'available', 'hybrid', 'https://portfolio.ryuadobe.com', NULL, 'https://linkedin.com/in/ryuadobe', 4.9, 35, 58, TRUE, NOW()),
(61, 'UX 리서치 및 사용성 테스트 전문가', '사용자 리서치와 사용성 테스트를 통한 데이터 기반 UX 개선 전문가입니다.', '["UX Research", "Usability Testing", "User Interview", "A/B Testing", "Analytics"]', 5, 'senior', 70000.00, 'available', 'onsite', 'https://portfolio.hongux.com', NULL, 'https://linkedin.com/in/hongux', 4.7, 23, 39, TRUE, NOW()),
(62, '비주얼 디자인 및 타이포그래피 전문가', '타이포그래피와 레이아웃을 중심으로 한 시각적 커뮤니케이션 디자인 전문가입니다.', '["Visual Design", "Typography", "Layout Design", "Graphic Design", "Brand Communication"]', 6, 'senior', 58000.00, 'available', 'remote', 'https://portfolio.chovisual.com', NULL, 'https://linkedin.com/in/chovisual', 4.6, 19, 33, TRUE, NOW()),
(63, '인터랙션 디자인 전문가', '사용자와 제품 간의 상호작용을 설계하는 인터랙션 디자인 전문가입니다.', '["Interaction Design", "Micro-interactions", "Animation", "Framer", "Principle"]', 4, 'mid', 68000.00, 'available', 'hybrid', 'https://portfolio.ahninteraction.com', NULL, 'https://linkedin.com/in/ahninteraction', 4.7, 16, 28, TRUE, NOW()),
(64, '서비스 디자인 및 고객 경험 전문가', '서비스 전반의 사용자 여정을 설계하고 고객 경험을 개선하는 전문가입니다.', '["Service Design", "Customer Experience", "Journey Mapping", "Service Blueprint", "Design Thinking"]', 5, 'senior', 72000.00, 'available', 'all', 'https://portfolio.yooservice.com', NULL, 'https://linkedin.com/in/yooservice', 4.8, 24, 41, TRUE, NOW()),
(65, '프로덕트 디자인 전문가', '사용자 중심의 제품 디자인과 프로덕트 전략 수립 전문가입니다.', '["Product Design", "Design Strategy", "User Research", "MVP Design", "Product Management"]', 6, 'senior', 75000.00, 'available', 'hybrid', 'https://portfolio.improduct.com', NULL, 'https://linkedin.com/in/improduct', 4.8, 27, 45, TRUE, NOW()),

-- 기획자 및 PM 프리랜서 (20명)
(66, 'IT 프로젝트 관리 전문가', 'PMP 자격을 보유한 IT 프로젝트 관리 전문가로, 애자일과 워터폴 방법론 모두 능숙합니다.', '["Project Management", "PMP", "Agile", "Scrum", "Waterfall", "JIRA"]', 8, 'expert', 85000.00, 'available', 'hybrid', 'https://portfolio.kimpm.com', NULL, 'https://linkedin.com/in/kimpm', 4.9, 40, 65, TRUE, NOW()),
(67, '서비스 기획 및 BM 설계 전문가', '디지털 서비스 기획과 비즈니스 모델 설계를 통해 성공적인 서비스 런칭을 이끕니다.', '["Service Planning", "Business Model", "Market Research", "Competitive Analysis", "Go-to-Market"]', 6, 'senior', 70000.00, 'available', 'all', 'https://portfolio.leeplan.com', NULL, 'https://linkedin.com/in/leeplan', 4.7, 28, 45, TRUE, NOW()),
(68, 'Product Owner 및 백로그 관리 전문가', 'Product Owner로서 제품 비전 수립부터 백로그 관리까지 제품 개발 전반을 리드합니다.', '["Product Owner", "Backlog Management", "User Story", "Product Strategy", "Stakeholder Management"]', 5, 'senior', 80000.00, 'available', 'remote', 'https://portfolio.parkpo.com', NULL, 'https://linkedin.com/in/parkpo', 4.8, 32, 52, TRUE, NOW()),
(69, 'Business Analyst 및 요구사항 분석 전문가', '비즈니스 요구사항 분석과 시스템 설계를 통해 프로젝트 성공을 보장합니다.', '["Business Analysis", "Requirements Analysis", "Process Modeling", "Use Case", "System Design"]', 7, 'expert', 75000.00, 'available', 'onsite', 'https://portfolio.choiba.com', NULL, 'https://linkedin.com/in/choiba', 4.8, 35, 58, TRUE, NOW()),
(70, 'Scrum Master 및 애자일 코치', 'CSM 자격을 보유한 Scrum Master로서 팀의 애자일 전환과 성숙도 향상을 지원합니다.', '["Scrum Master", "Agile Coach", "Team Facilitation", "Sprint Planning", "Retrospective"]', 6, 'senior', 78000.00, 'available', 'hybrid', 'https://portfolio.jungscrum.com', NULL, 'https://linkedin.com/in/jungscrum', 4.7, 29, 48, TRUE, NOW()),
(71, '전략 기획 및 시장 분석 전문가', '시장 동향 분석과 경쟁사 분석을 바탕으로 전략적 의사결정을 지원합니다.', '["Strategy Planning", "Market Analysis", "Competitive Intelligence", "SWOT Analysis", "Business Case"]', 8, 'expert', 90000.00, 'available', 'all', 'https://portfolio.kangstrategy.com', NULL, 'https://linkedin.com/in/kangstrategy', 4.9, 38, 62, TRUE, NOW()),
(72, '데이터 분석 및 BI 기획 전문가', 'SQL, Python을 활용한 데이터 분석과 BI 대시보드 구축으로 데이터 기반 의사결정을 지원합니다.', '["Data Analysis", "Business Intelligence", "SQL", "Python", "Tableau", "Dashboard"]', 5, 'senior', 72000.00, 'available', 'remote', 'https://portfolio.yoondata.com', NULL, 'https://linkedin.com/in/yoondata', 4.6, 24, 40, TRUE, NOW()),
(73, '운영 기획 및 프로세스 개선 전문가', '업무 프로세스 분석과 개선을 통해 조직의 운영 효율성을 극대화합니다.', '["Operations Planning", "Process Improvement", "Workflow Optimization", "KPI Management", "Lean Six Sigma"]', 7, 'expert', 68000.00, 'available', 'onsite', 'https://portfolio.limoperation.com', NULL, 'https://linkedin.com/in/limoperation', 4.7, 31, 51, TRUE, NOW()),
(74, '마케팅 기획 및 캠페인 관리 전문가', '디지털 마케팅 전략 수립부터 캠페인 실행, 성과 분석까지 마케팅 전반을 기획합니다.', '["Marketing Planning", "Campaign Management", "Digital Marketing", "Marketing Analytics", "Growth Hacking"]', 5, 'senior', 65000.00, 'available', 'hybrid', 'https://portfolio.hanmarketing.com', NULL, 'https://linkedin.com/in/hanmarketing', 4.6, 22, 38, TRUE, NOW()),
(75, '콘텐츠 기획 및 에디터', '브랜드 스토리텔링과 콘텐츠 전략을 통해 사용자 인게이지먼트를 극대화합니다.', '["Content Planning", "Content Strategy", "Copywriting", "Editorial", "Brand Storytelling"]', 4, 'mid', 55000.00, 'available', 'all', 'https://portfolio.ohcontent.com', NULL, 'https://linkedin.com/in/ohcontent', 4.5, 18, 32, FALSE, NOW()),
(76, '이벤트 기획 및 프로모션 전문가', '온오프라인 이벤트 기획과 프로모션 전략으로 브랜드 인지도와 매출 향상을 이끕니다.', '["Event Planning", "Promotion Strategy", "Campaign Execution", "Brand Activation", "Partnership"]', 6, 'senior', 60000.00, 'available', 'remote', 'https://portfolio.shinevent.com', NULL, 'https://linkedin.com/in/shinevent', 4.6, 25, 42, TRUE, NOW()),
(77, '디지털 트랜스포메이션 기획 전문가', '조직의 디지털 전환 전략 수립과 실행을 통해 비즈니스 혁신을 주도합니다.', '["Digital Transformation", "Change Management", "Technology Strategy", "Process Digitization", "Innovation"]', 9, 'expert', 95000.00, 'available', 'hybrid', 'https://portfolio.kwondigital.com', NULL, 'https://linkedin.com/in/kwondigital', 4.9, 42, 68, TRUE, NOW()),
(78, '모바일 서비스 기획자', '모바일 앱 서비스 기획과 UX 설계를 통해 사용자 친화적인 모바일 경험을 제공합니다.', '["Mobile Service Planning", "App Planning", "Mobile UX", "App Store Optimization", "Mobile Analytics"]', 4, 'mid', 68000.00, 'available', 'all', 'https://portfolio.seomobile.com', NULL, 'https://linkedin.com/in/seomobile', 4.7, 20, 35, TRUE, NOW()),
(79, '이커머스 기획 및 운영 전문가', '온라인 쇼핑몰 기획부터 운영, 마케팅까지 이커머스 전반의 비즈니스를 관리합니다.', '["E-commerce Planning", "Online Retail", "Merchandising", "Conversion Optimization", "Customer Journey"]', 6, 'senior', 70000.00, 'available', 'onsite', 'https://portfolio.moonecommerce.com', NULL, 'https://linkedin.com/in/moonecommerce', 4.8, 27, 46, TRUE, NOW()),
(80, '스타트업 사업 기획 전문가', '스타트업의 사업 모델 개발부터 투자 유치, 성장 전략까지 전반적인 사업 기획을 지원합니다.', '["Startup Planning", "Business Model Canvas", "Pitch Deck", "Investment", "Scaling Strategy"]', 5, 'senior', 75000.00, 'available', 'remote', 'https://portfolio.jangstartup.com', NULL, 'https://linkedin.com/in/jangstartup', 4.7, 23, 39, TRUE, NOW()),
(81, '혁신 기획 및 신사업 개발 전문가', '신사업 기회 발굴과 혁신 프로젝트 기획을 통해 기업의 지속 가능한 성장을 지원합니다.', '["Innovation Planning", "New Business Development", "Opportunity Assessment", "R&D Management", "Corporate Venturing"]', 8, 'expert', 88000.00, 'available', 'hybrid', 'https://portfolio.songinnovation.com', NULL, 'https://linkedin.com/in/songinnovation', 4.8, 36, 59, TRUE, NOW()),
(82, 'IT 컨설팅 및 솔루션 기획 전문가', 'IT 솔루션 기획과 시스템 통합 컨설팅을 통해 기업의 디지털 역량을 강화합니다.', '["IT Consulting", "Solution Architecture", "System Integration", "Technology Assessment", "Digital Strategy"]', 9, 'expert', 100000.00, 'available', 'all', 'https://portfolio.goconsulting.com', NULL, 'https://linkedin.com/in/goconsulting', 4.9, 45, 72, TRUE, NOW()),
(83, '그로스 해킹 및 성장 전략 전문가', '데이터 기반의 그로스 해킹과 성장 전략으로 서비스의 폭발적 성장을 이끕니다.', '["Growth Hacking", "Growth Strategy", "A/B Testing", "Funnel Optimization", "Viral Marketing"]', 4, 'mid', 78000.00, 'available', 'remote', 'https://portfolio.namgrowth.com', NULL, 'https://linkedin.com/in/namgrowth', 4.7, 19, 33, TRUE, NOW()),
(84, '플랫폼 비즈니스 기획 전문가', '플랫폼 비즈니스 모델 설계와 생태계 구축을 통해 네트워크 효과를 극대화합니다.', '["Platform Strategy", "Ecosystem Design", "Network Effects", "Marketplace", "Multi-sided Market"]', 6, 'senior', 82000.00, 'available', 'onsite', 'https://portfolio.wooplatform.com', NULL, 'https://linkedin.com/in/wooplatform', 4.8, 28, 47, TRUE, NOW()),
(85, '파트너십 및 제휴 기획 전문가', '전략적 파트너십과 제휴 기획을 통해 시너지 효과를 창출하고 사업 확장을 지원합니다.', '["Partnership Strategy", "Alliance Management", "Business Development", "Contract Negotiation", "Relationship Management"]', 7, 'expert', 80000.00, 'available', 'hybrid', 'https://portfolio.ryupartnership.com', NULL, 'https://linkedin.com/in/ryupartnership', 4.8, 33, 55, TRUE, NOW()),

-- 마케터 및 기타 전문가 프리랜서 (15명)
(86, 'SEO 및 검색엔진 마케팅 전문가', 'Google Analytics, Search Console을 활용한 SEO 최적화와 검색광고 운영 전문가입니다.', '["SEO", "SEM", "Google Analytics", "Google Ads", "Keyword Research", "Content Marketing"]', 5, 'senior', 65000.00, 'available', 'remote', 'https://portfolio.kimseo.com', NULL, 'https://linkedin.com/in/kimseo', 4.7, 26, 43, TRUE, NOW()),
(87, 'SNS 마케팅 및 인플루언서 전문가', 'Instagram, TikTok, YouTube 등 SNS 플랫폼 마케팅과 인플루언서 협업 전문가입니다.', '["Social Media Marketing", "Influencer Marketing", "Instagram", "TikTok", "YouTube", "Content Creation"]', 4, 'mid', 58000.00, 'available', 'all', 'https://portfolio.leesns.com', NULL, 'https://linkedin.com/in/leesns', 4.6, 22, 38, TRUE, NOW()),
(88, '퍼포먼스 마케팅 및 광고 운영 전문가', 'Facebook Ads, Google Ads 등 퍼포먼스 마케팅과 ROAS 최적화 전문가입니다.', '["Performance Marketing", "Facebook Ads", "Google Ads", "ROAS Optimization", "Conversion Tracking", "Attribution"]', 6, 'senior', 70000.00, 'available', 'hybrid', 'https://portfolio.parkperformance.com', NULL, 'https://linkedin.com/in/parkperformance', 4.8, 29, 48, TRUE, NOW()),
(89, '브랜드 마케팅 및 PR 전문가', '브랜드 전략 수립과 PR 캠페인을 통해 브랜드 인지도와 이미지를 향상시킵니다.', '["Brand Marketing", "Public Relations", "Brand Strategy", "Media Relations", "Crisis Management", "Brand Positioning"]', 7, 'expert', 75000.00, 'available', 'onsite', 'https://portfolio.choibrand.com', NULL, 'https://linkedin.com/in/choibrand', 4.8, 32, 52, TRUE, NOW()),
(90, '카피라이팅 및 콘텐츠 라이팅 전문가', '설득력 있는 카피라이팅과 SEO 최적화된 콘텐츠 제작 전문가입니다.', '["Copywriting", "Content Writing", "SEO Writing", "Marketing Copy", "Brand Voice", "Editorial"]', 5, 'senior', 50000.00, 'available', 'remote', 'https://portfolio.jungcopy.com', NULL, 'https://linkedin.com/in/jungcopy', 4.6, 24, 41, FALSE, NOW()),
(91, '기술 문서 작성 및 매뉴얼 제작 전문가', 'API 문서, 사용자 매뉴얼, 기술 가이드 등 기술 문서 작성 전문가입니다.', '["Technical Writing", "API Documentation", "User Manual", "Technical Guide", "Documentation Tools", "Markdown"]', 6, 'senior', 60000.00, 'available', 'all', 'https://portfolio.kangtech.com', NULL, 'https://linkedin.com/in/kangtech', 4.7, 21, 36, TRUE, NOW()),
(92, '블로그 운영 및 콘텐츠 제작 전문가', '기업 블로그 운영과 SEO 최적화된 콘텐츠 제작으로 트래픽 증대를 이끕니다.', '["Blog Management", "Content Creation", "SEO Content", "Content Strategy", "WordPress", "Social Media"]', 4, 'mid', 45000.00, 'available', 'hybrid', 'https://portfolio.yoonblog.com', NULL, 'https://linkedin.com/in/yoonblog', 4.5, 18, 32, FALSE, NOW()),
(93, '영어 번역 및 통역 전문가', 'TOEIC 990점, 영어 번역 및 동시통역, 비즈니스 영어 커뮤니케이션 전문가입니다.', '["English Translation", "Interpretation", "Business English", "Localization", "Proofreading", "Cross-cultural Communication"]', 8, 'expert', 55000.00, 'available', 'remote', 'https://portfolio.limenglish.com', NULL, 'https://linkedin.com/in/limenglish', 4.8, 35, 58, TRUE, NOW()),
(94, '일본어 번역 및 로컬라이징 전문가', 'JLPT N1, 일본어 번역 및 일본 시장 진출을 위한 로컬라이징 전문가입니다.', '["Japanese Translation", "Localization", "J-test", "Business Japanese", "Cultural Adaptation", "Market Research"]', 6, 'senior', 52000.00, 'available', 'onsite', 'https://portfolio.hanjapanese.com', NULL, 'https://linkedin.com/in/hanjapanese', 4.7, 23, 39, TRUE, NOW()),
(95, '재무 컨설팅 및 투자 분석 전문가', 'CPA 자격, 재무 분석과 투자 검토, 사업성 평가 및 재무 전략 수립 전문가입니다.', '["Financial Consulting", "Investment Analysis", "Business Valuation", "Financial Planning", "CPA", "Due Diligence"]', 10, 'expert', 90000.00, 'available', 'hybrid', 'https://portfolio.ohfinance.com', NULL, 'https://linkedin.com/in/ohfinance', 4.9, 38, 62, TRUE, NOW()),
(96, '인사 컨설팅 및 조직 개발 전문가', '인사 제도 설계와 조직 문화 개발, 인재 육성 프로그램 구축 전문가입니다.', '["HR Consulting", "Organizational Development", "Talent Management", "Performance Management", "Culture Transformation", "Leadership Development"]', 9, 'expert', 80000.00, 'available', 'all', 'https://portfolio.shinhr.com', NULL, 'https://linkedin.com/in/shinhr', 4.8, 34, 56, TRUE, NOW()),
(97, '법무 컨설팅 및 계약서 검토 전문가', '변호사 자격, 기업 법무 컨설팅과 계약서 검토, 컴플라이언스 체크 전문가입니다.', '["Legal Consulting", "Contract Review", "Compliance", "Corporate Law", "IP Law", "Risk Management"]', 12, 'expert', 120000.00, 'available', 'onsite', 'https://portfolio.kwonlegal.com', NULL, 'https://linkedin.com/in/kwonlegal', 4.9, 45, 75, TRUE, NOW()),
(98, 'IT 교육 및 강의 전문가', 'IT 기술 교육과 기업 임직원 대상 기술 교육, 온라인 강의 제작 전문가입니다.', '["IT Training", "Corporate Training", "Online Course", "Technical Education", "Curriculum Development", "E-learning"]', 7, 'expert', 70000.00, 'available', 'remote', 'https://portfolio.seotraining.com', NULL, 'https://linkedin.com/in/seotraining', 4.8, 31, 51, TRUE, NOW()),
(99, '멘토링 및 커리어 코칭 전문가', 'IT 직군 멘토링과 커리어 전환 코칭, 개발자 성장 전략 수립 전문가입니다.', '["Mentoring", "Career Coaching", "Professional Development", "Skill Assessment", "Goal Setting", "Leadership Coaching"]', 8, 'expert', 65000.00, 'available', 'hybrid', 'https://portfolio.moonmentor.com', NULL, 'https://linkedin.com/in/moonmentor', 4.7, 29, 48, TRUE, NOW()),
(100, '빅데이터 분석 및 시각화 전문가', 'Python, R을 활용한 빅데이터 분석과 Tableau, Power BI를 통한 데이터 시각화 전문가입니다.', '["Big Data", "Data Analysis", "Python", "R", "Tableau", "Power BI", "Machine Learning", "Statistics"]', 6, 'senior', 85000.00, 'available', 'all', 'https://portfolio.jangdata.com', NULL, 'https://linkedin.com/in/jangdata', 4.8, 27, 44, TRUE, NOW());

-- 테이블 데이터 확인 쿼리
SELECT COUNT(*) as total_users FROM users;
SELECT COUNT(*) as total_freelancers FROM freelancers;

-- 프리랜서 카테고리별 통계
SELECT 
    CASE 
        WHEN title LIKE '%개발%' OR title LIKE '%프로그래밍%' OR title LIKE '%엔지니어%' THEN '개발자'
        WHEN title LIKE '%디자인%' OR title LIKE '%UI%' OR title LIKE '%UX%' THEN '디자이너'
        WHEN title LIKE '%기획%' OR title LIKE '%PM%' OR title LIKE '%매니저%' THEN '기획자'
        ELSE '기타'
    END as category,
    COUNT(*) as count
FROM freelancers 
GROUP BY category;

-- 완료 메시지
SELECT '100명의 프리랜서 데이터가 성공적으로 생성되었습니다!' as message;